version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: always

  rosblox-studio:
    image: ghcr.io/rosblox/studio:latest
    volumes:
      - ./studio/layout.json:/src/layout.json
    ports:
      - 8080:8080
    restart: always

  ros-rosbridge-suite:
    image: ghcr.io/rosblox/ros-rosbridge-suite:humble
    ports:
      - 9090:9090
    restart: always
    command: ros2 launch rosbridge_server rosbridge_websocket_launch.xml

  ros-navigation2:
    image: ghcr.io/rosblox/ros-navigation2:humble
    volumes:
      - ./nav2_bringup/nav2_bringup_launch.py:/opt/ros/humble/share/nav2_bringup/launch/nav2_bringup_launch.py
      - ./nav2_bringup/nav2_params.yaml:/opt/ros/humble/share/nav2_bringup/params/nav2_params.yaml
      - ./nav2_bringup/goat_world.yaml:/opt/ros/humble/share/nav2_bringup/maps/goat_world.yaml
      - ./nav2_bringup/goat_world_empty.pgm:/opt/ros/humble/share/nav2_bringup/maps/goat_world_empty.pgm
    restart: always
    network_mode: "host"
    command: ros2 launch nav2_bringup nav2_bringup_launch.py
